### ISSUE TITLE
Some Ideas

### ISSUE THREAD

**Issue by academo** [sn0opr/ionic-autocomplete#3]
HI!

I would like to purpose some ideas for this component:
- instead of using a callback is probably better to change the ngModel and the controller can watch for changes if needed.
- Allow the 'Enter' button in virtual keyboard, currently the only way to finish the modal is to click an option or outside
- Allow to pass a function to 'items' which can be called on every user key change so the controller can use a service by example to provide the list of elements to be autocompleted, this can support promises for ajax request by example.
- Add a 'mandatory' to select in case of one of the elements need to be selected, imagine a 'Cities' selector

I can help you to develop some of the ideas :)

**Comment by sn0opr** [comment]
Hi academo.
Thank you for proposing ideas, they are great.
It would be great if you contribute in this project!
